services:
  impostor-nextjs:
    image: 'ghcr.io/tranadam/question-impostor:latest'
    container_name: impostor-app
    restart: unless-stopped
    ports:
      - '8302:3000'
    environment:
      - NODE_ENV=production
    env_file:
      - .env
